ROLE_SKILL_CATALOG = {
    "Frontend Developer": {
        "react",
        "next.js",
        "typescript",
        "javascript",
        "html",
        "css",
        "tailwind",
        "redux",
    },
    "Backend Developer": {
        "python",
        "django",
        "fastapi",
        "postgresql",
        "rest api",
        "redis",
        "celery",
        "docker",
    },
    "Full Stack Developer": {
        "react",
        "next.js",
        "typescript",
        "python",
        "django",
        "postgresql",
        "rest api",
        "docker",
    },
    "Data Analyst": {
        "python",
        "sql",
        "excel",
        "power bi",
        "tableau",
        "pandas",
        "numpy",
        "statistics",
    },
    "AI Engineer": {
        "python",
        "machine learning",
        "langchain",
        "langgraph",
        "llm",
        "prompt engineering",
        "vector database",
        "api integration",
    },
}

KNOWN_SKILLS = sorted({skill for skills in ROLE_SKILL_CATALOG.values() for skill in skills})
