# Generated by Django 6.0.3 on 2026-04-02 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphthread',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.cv'),
        ),
    ]
